# /etc/grafana/provisioning/datasources/datasources.yaml
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.0.0.1:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://10.0.0.1:3100

  # If you have the Alertmanager plugin installed:
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://10.0.0.1:9093
