apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.0.0.1:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://10.0.0.1:3100
    editable: false
