
services:
  react-app:
    build: ./fadelfront/
    ports:
      - "80:80"
    image: stephb421/buildesp-app:latest

  express-api:
    build: ./api/
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    image: stephb421/buildesp-back:latest

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: