services:
  backend:
    volumes:
      - ./backend:/app
    extends:
      file: ./backend/docker-compose.yml
      service: backend

  db:
    extends:
      file: ./backend/docker-compose.yml
      service: db

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend

networks:
  buildesp_network:
    name: buildesp_network
    driver: bridge

volumes:
  mysql-data:
