version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=neighborrow_dev_db
      - JWT_SECRET=cD8WjQGtWK1TiUmu0hufQ8KjkOLxCNAsgZa3mbIdlXuPShMYYIq9OTA4U8PfM4SZGNoUFxmFl3VrBoxRxxbrLA==
      - ALLOWED_ORIGINS=http://172.31.41.254:80 # 🔹 Autorisation des requêtes du Front
    depends_on:
      db:
        condition: service_healthy  # ✅ Attendre que la DB soit prête avant de démarrer
    image: stephb421/buildesp-backend:latest
    restart: always
    networks:
      - buildesp_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neighborrow_dev_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - buildesp_network
    healthcheck:  # ✅ Vérification automatique si la DB est prête
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:

networks:
  buildesp_network:
    external: true
