services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://${REACT_APP_FRONTEND_IP}:80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    depends_on:
      db:
        condition: service_healthy
    image: stephb421/buildesp-backend:latest
    restart: always
    networks:
      - buildesp_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - buildesp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /home/admuser/Repo810/back_student/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log  # Ajout pour récupérer les logs systèmes (optionnel)
    command: -config.file=/etc/promtail/promtail-config.yml -config.expand-env=true
    restart: always
    networks:
      - buildesp_network
      
volumes:
  mysql-data:

networks:
  buildesp_network:
    driver: bridge
