version: "2.33.0"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    image: stephb421/buildesp-backend:latest
    depends_on:
      - db
    networks:
      - buildesp_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql # 🔹 Ne plus redéfinir ce volume ici
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - buildesp_network

networks:
  buildesp_network:
    external: true
