version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=neighborrow_dev_db
      - JWT_SECRET=cD8WjQGtWK1TiUmu0hufQ8KjkOLxCNAsgZa3mbIdlXuPShMYYIq9OTA4U8PfM4SZGNoUFxmFl3VrBoxRxxbrLA==
      - ALLOWED_ORIGINS=http://${PRIVATE_IP_FRONT}:80 # 🔹 Autorisation des requêtes du Front
    depends_on:
      - db
    image: stephb421/buildesp-backend:latest
    networks:
      - buildesp_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neighborrow_dev_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - buildesp_network

volumes:
  mysql-data:

networks:
  buildesp_network:
    external: true
