server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.31.41.254:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: database_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: database_logs
          __path__: /var/log/mysql.log  # Assurez-vous du bon chemin

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: "(?P<image_name>[^|]+).(?P<container_name>[^|]+).(?P<image_id>[^|]+).(?P<container_id>[^|]+)"
          source: "tag"

      - labels:
          image_name:
          container_name:
          image_id:
          container_id:
