global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 10.0.0.1:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 10.0.0.1:9090

  - job_name: node
    static_configs:
      - targets:
          - 10.0.0.1:9100
  
  - job_name: 'loki'
    static_configs:
      - targets: ['10.0.0.1:3100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://10.0.0.1//  # Remplacez par l'URL de votre site web
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance  
      - target_label: __address__
        replacement: 10.0.0.1:9115  # Adresse de Blackbox Exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['10.0.0.1:9121']
