global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: 'jmeter'
    static_configs:
      - targets: ['localhost:9270']
  
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
<<<<<<< Updated upstream:frontend/monitoring/prometheus.yml
          - http://15.237.77.97/  # Remplacez par l'URL de votre site web
=======
          - http://neigborrow.heiferl.fr   # Replace with your target URL
>>>>>>> Stashed changes:monitoring/prometheus.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance  
      - target_label: __address__
<<<<<<< Updated upstream:frontend/monitoring/prometheus.yml
        replacement: blackbox_exporter:9115  # Adresse de Blackbox Exporter

=======
        replacement: blackbox_exporter:9115
        
>>>>>>> Stashed changes:monitoring/prometheus.yml
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
