name: Fullstack-CI-CD-Pipeline

on:
  push:
    branches:
      - DevOps_ESP-51
  pull_request:
    branches:
      - DevOps_ESP-51
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  COMPOSE_FILE: docker-compose.yml

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  init:
    runs-on: ubuntu-22.04
    outputs:
      node_modules_frontend: ${{ steps.cache-frontend.outputs.cache-hit }}
      node_modules_backend: ${{ steps.cache-backend.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure npm cache
        run: npm config set cache .npm --global

      - name: Cache Node.js modules (frontend)
        id: cache-frontend
        uses: actions/cache@v4
        with:
          path: |
            frontend/app/node_modules
            ~/.npm
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/app/package-lock.json') }}
          restore-keys: ${{ runner.os }}-frontend-

      - name: Install frontend dependencies
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        working-directory: frontend/app
        run: npm ci --prefer-offline --no-audit

      - name: Cache Node.js modules (backend)
        id: cache-backend
        uses: actions/cache@v4
        with:
          path: |
            backend/api/node_modules
            ~/.npm
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/api/package-lock.json') }}
          restore-keys: ${{ runner.os }}-backend-

      - name: Install backend dependencies
        if: steps.cache-backend.outputs.cache-hit != 'true'
        working-directory: backend/api
        run: npm ci --prefer-offline --no-audit

  quality:
    needs: init
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        project:
          - { path: 'frontend/app', name: 'frontend' }
          - { path: 'backend/api', name: 'backend' }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore Node.js modules
        uses: actions/cache@v4
        with:
          path: ${{ matrix.project.path }}/node_modules
          key: ${{ runner.os }}-${{ matrix.project.name }}-${{ hashFiles('${{ matrix.project.path }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.project.name }}-

      - name: Install quality tools
        working-directory: ${{ matrix.project.path }}
        run: npm install --save-dev eslint prettier eslint-config-prettier eslint-plugin-prettier

      - name: Lint and Format Check
        working-directory: ${{ matrix.project.path }}
        run: |
          npx eslint . --max-warnings=0
          npx prettier --check .
        continue-on-error: true

  security:
    needs: init
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            frontend/app/node_modules
            backend/api/node_modules
          key: ${{ runner.os }}-*-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-*-

      - name: Dependency Audit
        run: |
          echo "Running npm audit --fix and depcheck for frontend/app"
          cd frontend/app
          npm audit  --omit=dev
          npx depcheck
          npm audit fix

          echo "Running npm audit --fix and depcheck for backend/api"
          cd ../../backend/api
          npm audit  --omit=dev
          npx depcheck
          npm audit fix
        continue-on-error: true

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "security"

  test:
    needs: init
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            frontend/app/node_modules
            backend/api/node_modules
          key: ${{ runner.os }}-*-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-*-

      - name: Run Unit Tests
        run: |
          cd backend/api && npm test -- --coverage
          cd frontend/app && npm test -- --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-deploy:
    needs: [quality, security, test]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        project:
          - { context: 'frontend/app', image_key: 'DOCKER_IMAGE_FRONTEND' }
          - { context: 'backend/api', image_key: 'DOCKER_IMAGE_BACKEND' }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            frontend/app/node_modules
            backend/api/node_modules
          key: ${{ runner.os }}-*-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-*-

      - name: Build applications
        working-directory: ${{ matrix.project.context }}
        run: npm run build -- --prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.project.context }}
          push: true
          tags: |
            ${{ env[matrix.project.image_key] }}:latest
            ${{ env[matrix.project.image_key] }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max