name: Fullstack-CI-Pipeline

on:
  push:
    branches:
      - DevOps_ESP-51
  pull_request:
    branches:
      - DevOps_ESP-51

env:
  NODE_VERSION: '20.x'
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_API_TOKEN }}

jobs:
  init:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

  quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ env.CODACY_PROJECT_TOKEN }}
          # Optionnel : Spécifiez le répertoire à analyser
          directory: .