name: Deploy Frontend

on:
  push:
    branches:
      - DevOps_ESP-130
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_FRONT_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.MY_FRONT_SERVER }}@${{ secrets.EC2_FRONT_HOST }} << 'EOF'
            echo "🚀 Déploiement du Frontend & Monitoring..."

            cd /var/www/front/frontend

            echo "📥 Sauvegarde temporaire du .env..."
            git stash push -m "Sauvegarde temporaire du .env" .env || echo "Aucun fichier .env à stasher"

            # Stasher toutes les autres modifications locales
            git stash push -m "Sauvegarde des modifications locales" --keep-index || echo "Aucune modification locale à stasher"

            echo "📥 Pulling latest changes..."
            git checkout DevOps_ESP-130 || git checkout -b DevOps_ESP-130
            git pull origin DevOps_ESP-130 --rebase

            echo "📥 Restauration du .env..."
            git stash pop || echo "⚠️ Aucun stash à restaurer"

            echo "🧹 Nettoyage des fichiers inutiles..."
            rm -rf /var/www/front/backend /var/www/front/cypress

            cd app
            if [ -f package.json ]; then
              echo "📦 Installing dependencies..."
              npm install
              echo "⚙️  Building frontend..."
              npm run build
            else
              echo "❌ ERREUR: package.json non trouvé."
              exit 1
            fi

            echo "🔄 Mise à jour et redémarrage des conteneurs Docker..."
            docker-compose down
            sudo docker system prune -af
            docker network create buildesp_network || echo "Réseau déjà existant"
            docker-compose build
            docker-compose up -d

            echo "✅ Déploiement Frontend & Monitoring terminé !"
          EOF
