name: Test-Pipeline

on:
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd backend/api
          npm install
          cd ../../frontend/app
          npm install

      - name: Run Unit Tests
        run: |
          cd backend/api
          npm test
          cd ../../frontend/app
          npm test
